---

name: Functional-Tests Execution for PRs

on:
  push:
    branches: [latest]
    paths:
      - '**.py'
      - 'tests/**.py'
      - 'scripts/functional_test.sh'
      - '.github/workflows/functional_test.yml'
  pull_request_target:
    branches: ['latest']
    paths:
      - '**.py'
      - 'tests/**.py'
      - 'scripts/functional_test.sh'
      - '.github/workflows/functional_test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: test

    steps:
      - uses: actions/checkout@v5

      - name: Test Connection
        if: ${{ steps.modules_to_test.outputs.count != 0 }}
        run: |
          echo '10.0.0.1 ${{ vars.CI_TEST_FIREWALL_1 }}' | sudo tee -a /etc/hosts
          https_proxy=${{ secrets.CI_TEST_PROXY }} curl --fail-with-body https://${{ vars.CI_TEST_FIREWALL_1 }} --insecure > /tmp/test.html

          if grep -q 'DNS Rebind attack' < /tmp/test.html
          then
            echo 'ERROR: Firewall Hostname ${{ vars.CI_TEST_FIREWALL_1 }} not configured!'
            exit 1
          fi
        shell: bash

      - name: Install requirements
        if: ${{ steps.modules_to_test.outputs.count != 0 }}
        run: |
          pip install -r requirements.txt > /dev/null
          pip install -r requirements_test.txt > /dev/null
        shell: bash

      - name: Running Integration-Tests
        if: ${{ steps.modules_to_test.outputs.count != 0 }}
        run: |
          echo "${{ secrets.CI_TEST_API_CREDENTIALS }}" > /tmp/api_credentials.txt
          chmod 600 /tmp/api_credentials.txt
          bash scripts/functional_test.sh | tee -a /tmp/test.log
        shell: bash
        env:
          TEST_FIREWALL: ${{ vars.CI_TEST_FIREWALL_1 }}
          TEST_API_CREDS: /tmp/api_credentials.txt
          HTTPS_PROXY: ${{ secrets.CI_TEST_PROXY }}
          PYTHONUNBUFFERED: 1
          PY_COLORS: 1

      - uses: actions/upload-artifact@v4
        with:
          name: test-results-pr-${{ github.event.number }}
          path: /tmp/test.log
          retention-days: 14
